Repository neuro-inc/platform-storage-api, pull requests merged in 2021-12, with the labels that each got.

#520 Cleanup deployment workflows
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  Makefile
Labels: dependencies

#521 Cleanup deployment workflows
  .github/workflows/ci.yaml
  Makefile
Labels: dependencies

#527 Publish image to ecr
  setup.cfg
Labels: dependencies

#496 Show symlink status in LISTSTATUS and GETFILESTATUS
  platform_storage_api/fs/local.py
  tests/unit/test_fs_local.py
Labels: enhancement

#534 Setup shed
  .editorconfig
  .pre-commit-config.yaml
  platform_storage_api/api.py
  platform_storage_api/cache.py
  platform_storage_api/fs/local.py
  platform_storage_api/security.py
  setup.cfg
  tests/integration/test_api.py
  tests/integration/test_api_sharing_resources.py
  tests/integration/test_api_websocket.py
  tests/test_smoke.py
  tests/unit/test_cache.py
Labels: dependencies

#535 Setup shed
  .pre-commit-config.yaml
Labels: dependencies

#539 Setup shed
  .pre-commit-config.yaml
Labels: dependencies

#541 Setup shed
  .pre-commit-config.yaml
  setup.cfg
Labels: dependencies

#543 Setup shed
  .pre-commit-config.yaml
  setup.cfg
Labels: dependencies

#542 Escape special characters in a path when check permissions
  platform_storage_api/security.py
Labels: bug
